const $=id=>document.getElementById(id),program=$("program"),preview=$("preview");
const API="https://api.github.com/repos/Ashok-Kumar-Yadaw/TV-Playout/contents/videos?ref=main";
const base=new URL(".",location.href);
let S=JSON.parse(localStorage.getItem("tvv6")||"null")||{chs:[[],[],[],[]],ch:0,i:0,logs:[]},previewI=0;
function save(){localStorage.setItem("tvv6",JSON.stringify(S))}
function log(x){S.logs.push(new Date().toTimeString().slice(0,8)+" • "+x);S.logs=S.logs.slice(-120);save();$("log").textContent=S.logs.slice().reverse().join("\n")}
function url(s){return /^https?:|^blob:/.test(s)?s:new URL(s.split("/").map(encodeURIComponent).join("/"),base).href}
function fmt(n){n=Math.max(0,Math.floor(n||0));return[Math.floor(n/3600),Math.floor(n%3600/60),n%60].map(x=>String(x).padStart(2,"0")).join(":")}
function channels(){$("channels").innerHTML=S.chs.map((_,i)=>`<button class="ch ${i===S.ch?"active":""}" onclick="switchCh(${i})">CH ${i+1}</button>`).join("")}
function switchCh(i){S.ch=i;S.i=0;render();channels();log("CH "+(i+1))}
function render(){let l=S.chs[S.ch];$("playlist").innerHTML=l.map((x,i)=>`<div class="item ${i===S.i?"active":""}"><b>${i+1}</b><span>${x.title}<small>${x.src}</small></span><button onclick="previewItem(${i})">PREVIEW</button><button onclick="take(${i})">TAKE</button></div>`).join("")||'<p class="hint">No MP4 found. Scan करें।</p>';$("now").textContent=l[S.i]?.title||"—";$("next").textContent=(l[S.i+1]||l[0])?.title||"—";$("chbug").textContent="CH "+(S.ch+1);$("log").textContent=S.logs.slice().reverse().join("\n")}
function previewItem(i){let x=S.chs[S.ch][i];if(!x)return;previewI=i;preview.src=url(x.src);$("previewTitle").textContent=x.title;preview.load();preview.play().catch(()=>{});log("PREVIEW • "+x.title)}
function take(i){let x=S.chs[S.ch][i];if(!x)return;S.i=i;program.src=url(x.src);program.load();render();program.play().catch(()=>{$("state").textContent="PRESS PLAY"});log("TAKE • "+x.title)}
async function scan(){ $("scanStatus").textContent="SCANNING...";try{let r=await fetch(API,{cache:"no-store"});if(!r.ok)throw Error("GitHub API "+r.status);let d=await r.json();let mp4=d.filter(x=>x.type==="file"&&/\.mp4$/i.test(x.name));S.chs[0]=mp4.map(x=>({src:"videos/"+x.name,title:x.name}));S.i=0;save();$("scanStatus").textContent=mp4.length+" MP4 FOUND";render();log("SCAN • "+mp4.length+" MP4")}catch(e){$("scanStatus").textContent="SCAN ERROR";log("SCAN ERROR • "+e.message)}}
$("scan").onclick=scan;$("take").onclick=()=>take(previewI);$("play").onclick=()=>program.play().catch(()=>{});$("pause").onclick=()=>program.pause();$("stop").onclick=()=>{program.pause();program.currentTime=0;log("STOP")};$("estop").onclick=()=>{program.pause();program.removeAttribute("src");program.load();log("E-STOP")};
$("nextBtn").onclick=()=>{let l=S.chs[S.ch];if(!l.length)return;if(S.i+1<l.length)S.i++;else if($("loop").checked)S.i=0;else return;take(S.i)};
program.onloadedmetadata=()=>{$("state").textContent="READY"};program.onplaying=()=>{$("state").textContent="PLAYING"};program.ontimeupdate=()=>{$("remain").textContent=fmt(program.duration-program.currentTime)};program.onended=()=>{if($("auto").checked||$("loop").checked)$("nextBtn").click()};program.onerror=()=>{let x=S.chs[S.ch][S.i];$("state").textContent="MEDIA ERROR";log("MEDIA ERROR • "+(x?.src||""))};
$("add").onclick=()=>{let src=$("src").value.trim();if(!src)return;S.chs[S.ch].push({src,title:$("title").value.trim()||src.split("/").pop()});save();render();$("src").value="";$("title").value="";log("ADD • "+src)};
$("lowerBtn").onclick=()=>{$("lower").textContent=$("lowerText").value||"TV PROGRAM";$("lower").style.display="block";log("LOWER THIRD ON")};$("breakingBtn").onclick=()=>{$("breaking").textContent=$("breakingText").value||"BREAKING NEWS";$("breaking").style.display="block";log("BREAKING ON")};$("clearGraphics").onclick=()=>{$("lower").style.display="none";$("breaking").style.display="none";log("GRAPHICS CLEAR")};
function clock(){let d=new Date();$("clock").textContent=d.toTimeString().slice(0,8);if($("schedule").checked){let t=d.toTimeString().slice(0,5),i=S.chs[S.ch].findIndex(x=>x.time===t);if(i>=0&&i!==S.i)take(i)}}setInterval(clock,1000);clock();channels();render();scan();