const $=id=>document.getElementById(id),player=$("player"),preview=$("preview");
let S=JSON.parse(localStorage.getItem("tvv5fixed")||"null")||{chs:[[],[],[],[]],ch:0,i:0,logs:[]},previewI=0,base=new URL(".",location.href);
function save(){localStorage.setItem("tvv5fixed",JSON.stringify(S))} function log(x){S.logs.push(new Date().toTimeString().slice(0,8)+" • "+x);S.logs=S.logs.slice(-100);save();$("log").textContent=S.logs.slice().reverse().join("\n")}
function url(s){if(/^blob:|^https?:|^data:/.test(s))return s;return new URL(s.replace(/^\.\//,""),base).href}
function fmt(n){n=Math.max(0,Math.floor(n||0));return[Math.floor(n/3600),Math.floor(n%3600/60),n%60].map(x=>String(x).padStart(2,"0")).join(":")}
function renderChannels(){channels.innerHTML=S.chs.map((_,i)=>`<button class="ch ${i==S.ch?'active':''}" onclick="S.ch=${i};S.i=0;render();renderChannels();log('CH '+(i+1))">CH ${i+1}</button>`).join("")}
function render(){let l=S.chs[S.ch];$("count").textContent=l.length+" EVENTS";$("playlist").innerHTML=l.map((x,i)=>`<div class="item ${i==S.i?'active':''}"><b>${x.time||'--:--'}</b><span>${x.title}<small> • ${x.type} • ${x.dur}</small></span><button onclick="previewItem(${i})">PREVIEW</button><button onclick="take(${i})">TAKE</button></div>`).join("");let c=l[S.i],n=l[S.i+1]||l[0];$("now").textContent=c?.title||"—";$("next").textContent=n?.title||"—";$("bug").textContent="CH "+(S.ch+1);$("log").textContent=S.logs.slice().reverse().join("\n")}
function previewItem(i){let x=S.chs[S.ch][i];if(!x)return;previewI=i;preview.src=url(x.src);$("previewTitle").textContent=x.title;preview.load();preview.play().catch(()=>{});log("PREVIEW • "+x.title)}
function take(i){let x=S.chs[S.ch][i];if(!x)return;S.i=i;player.src=url(x.src);player.load();render();player.play().catch(()=>{$("state").textContent="PRESS PLAY"});log("TAKE • "+x.title)}
$("take").onclick=()=>take(previewI);$("play").onclick=()=>player.play();$("pause").onclick=()=>player.pause();$("stop").onclick=()=>{player.pause();player.currentTime=0;log("STOP")};
$("nextBtn").onclick=()=>{let l=S.chs[S.ch];if(!l.length)return;if(S.i+1<l.length)S.i++;else if($("loop").checked)S.i=0;else return;take(S.i)};
player.onloadedmetadata=()=>{$("state").textContent="READY"};player.onplaying=()=>{$("state").textContent="PLAYING"};player.ontimeupdate=()=>{$("remain").textContent=fmt(player.duration-player.currentTime)};player.onended=()=>{if($("auto").checked||$("loop").checked)$("nextBtn").click()};player.onerror=()=>{ $("state").textContent="MEDIA ERROR";log("MEDIA ERROR • "+(S.chs[S.ch][S.i]?.src||""))};
$("add").onclick=()=>{let src=$("src").value.trim();if(!src)return alert("videos/file.mp4 path डालें");S.chs[S.ch].push({src,title:$("title").value.trim()||src.split("/").pop(),time:$("time").value||"--:--",dur:$("dur").value,type:$("type").value});save();render();$("src").value="";$("title").value="";log("ADD • "+src)};
$("upload").onclick=()=>{let fs=[...$("picker").files];if(!fs.length)return alert("पहले MP4 select करें");fs.forEach(f=>S.chs[S.ch].push({src:URL.createObjectURL(f),title:f.name,time:"--:--",dur:"LOCAL",type:"PROGRAM"}));save();render();log(fs.length+" local video(s) added")};
function clock(){let d=new Date();$("clock").textContent=d.toTimeString().slice(0,8);if($("schedule").checked){let t=d.toTimeString().slice(0,5),i=S.chs[S.ch].findIndex(x=>x.time===t);if(i>=0&&i!==S.i)take(i)}}setInterval(clock,1000);clock();renderChannels();render();